

CREATE TABLE IF NOT EXISTS users (
  id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name   VARCHAR(255)  NOT NULL,
  email  VARCHAR(512)  NOT NULL,
  CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description  VARCHAR(512) NOT NULL,
  requestor_id BIGINT       NOT NULL,
  CONSTRAINT fk_requests_user
    FOREIGN KEY (requestor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(255)  NOT NULL,
  description  VARCHAR(512)  NOT NULL,
  is_available BOOLEAN       NOT NULL,
  owner_id     BIGINT        NOT NULL,
  request_id   BIGINT,
  CONSTRAINT fk_items_owner
    FOREIGN KEY (owner_id)   REFERENCES users(id)    ON DELETE CASCADE,
  CONSTRAINT fk_items_request
    FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS bookings (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id    BIGINT NOT NULL,
  booker_id  BIGINT NOT NULL,
  status     VARCHAR(50) NOT NULL
             CHECK (status IN ('WAITING','APPROVED','REJECTED','CANCELED')),
  CONSTRAINT fk_bookings_item
    FOREIGN KEY (item_id)   REFERENCES items(id)  ON DELETE CASCADE,
  CONSTRAINT fk_bookings_booker
    FOREIGN KEY (booker_id) REFERENCES users(id)  ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text      VARCHAR(1000) NOT NULL,
  item_id   BIGINT        NOT NULL,
  author_id BIGINT        NOT NULL,
  CONSTRAINT fk_comments_item
    FOREIGN KEY (item_id)   REFERENCES items(id)  ON DELETE CASCADE,
  CONSTRAINT fk_comments_author
    FOREIGN KEY (author_id) REFERENCES users(id)  ON DELETE CASCADE
);

ALTER TABLE requests
  ADD COLUMN IF NOT EXISTS created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now();

ALTER TABLE comments
  ADD COLUMN IF NOT EXISTS created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now();


ALTER TABLE bookings DROP CONSTRAINT IF EXISTS chk_booking_time;
ALTER TABLE bookings ADD CONSTRAINT chk_booking_time CHECK (start_date < end_date);



CREATE INDEX IF NOT EXISTS idx_items_owner      ON items(owner_id);
CREATE INDEX IF NOT EXISTS idx_items_available  ON items(is_available);

CREATE INDEX IF NOT EXISTS idx_requests_requestor ON requests(requestor_id);

CREATE INDEX IF NOT EXISTS idx_bookings_item_start   ON bookings(item_id, start_date);
CREATE INDEX IF NOT EXISTS idx_bookings_booker_start ON bookings(booker_id, start_date);
CREATE INDEX IF NOT EXISTS idx_bookings_status       ON bookings(status);
